matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8 gcc-4.8-plugin-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8 gcc-8-plugin-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

language: c
compiler:
  - gcc

language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install six pygments graphviz lxml

script: make
