os: linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9 gcc-9-plugin-dev
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

language: c
compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-six python-pygments graphviz python-lxml

script:
- pwd=$(pwd -P)
- mkdir build
- cd build
- make -f $pwd/Makefile srcdir=$pwd/
