#include <gcc-plugin.h>
#include "tree.h"

struct PyGccLocation {
     PyObject_HEAD
     location_t loc;
};

struct PyGccTree {
     PyObject_HEAD
     tree t;
};

int
gcc_python_autogenerated_tree_init_types(void);

void
gcc_python_autogenerated_tree_add_types(PyObject *m);

PyTypeObject*
gcc_python_autogenerated_tree_type_for_tree(tree t);

extern PyTypeObject gcc_Location;
