#include <Python.h>
#include "gcc-python.h"

PyObject *
gcc_python_make_wrapper_tree(tree t)
{
    PyTypeObject* tp;
  
    tp = gcc_python_autogenerated_tree_type_for_tree(t);
    assert(tp);
    printf("tp:%p\n", tp);

    /* For now, just return the type: */
    Py_INCREF(tp);
    return (PyObject*)tp;

    //PyObject_Call(
}
