from maketreetypes import iter_tree_types

from cpybuilder import *

tree_types = list(iter_tree_types())
# FIXME: truncate the list, for ease of development:
#tree_types = list(iter_tree_types())[:3]

cu = CompilationUnit()
cu.add_include('gcc-python.h')
cu.add_include('gcc-python-wrappers.h')
cu.add_include('gcc-plugin.h')
cu.add_include("tree.h")

modinit_preinit = ''
modinit_postinit = ''

cu.add_defn("""
static PyObject *
gcc_Location_get_file(struct PyGccLocation *self, void *closure)
{
    return PyString_FromString(LOCATION_FILE(self->loc));
}
""")
cu.add_defn("""
static PyObject *
gcc_Location_get_line(struct PyGccLocation *self, void *closure)
{
    return PyInt_FromLong(LOCATION_LINE(self->loc));
}
""")

getsettable = PyGetSetDefTable('gcc_Location_getset_table',
                               [PyGetSetDef('file', 'gcc_Location_get_file', None, 'Name of the source file'),
                                PyGetSetDef('line', 'gcc_Location_get_line', None, 'Line number within source file')])
cu.add_defn(getsettable.c_defn())

pytype = PyTypeObject(name = 'gcc_Location',
                      localname = 'Location',
                      tp_name = 'gcc.Location',
                      struct_name = 'struct PyGccLocation',
                      tp_dealloc = 'NULL',
                      tp_repr = 'NULL',
                      tp_methods = 'NULL',
                      tp_init = 'NULL',
                      tp_new = 'PyType_GenericNew')
cu.add_defn(pytype.c_defn())
modinit_preinit += "\n    %s.tp_getset = gcc_Location_getset_table;\n" % pytype.name
modinit_preinit += pytype.c_invoke_type_ready()
modinit_postinit += pytype.c_invoke_add_to_module()

cu.add_defn("""
static PyObject *
gcc_Tree_get_location(struct PyGccTree *self, void *closure)
{
    return gcc_python_make_wrapper_location(DECL_SOURCE_LOCATION(self->t));
}
""")

getsettable = PyGetSetDefTable('gcc_Tree_getset_table',
                               [PyGetSetDef('location', 'gcc_Tree_get_location', None, 'Location')])
cu.add_defn(getsettable.c_defn())

pytype = PyTypeObject(name = 'gcc_TreeType',
                      localname = 'Tree',
                      tp_name = 'gcc.Tree',
                      struct_name = 'struct PyGccTree',
                      tp_dealloc = 'NULL',
                      tp_repr = 'NULL',
                      tp_methods = 'NULL',
                      tp_init = 'NULL',
                      tp_new = 'PyType_GenericNew')
cu.add_defn(pytype.c_defn())
modinit_preinit += "\n    %s.tp_getset = gcc_Tree_getset_table;\n" % pytype.name
modinit_preinit += pytype.c_invoke_type_ready()
modinit_postinit += pytype.c_invoke_add_to_module()

for tree_type in tree_types:
    pytype = PyTypeObject(name = 'gcc_%sType' % tree_type.camel_cased_string(),
                          localname = tree_type.camel_cased_string(),
                          tp_name = 'gcc.%s' % tree_type.camel_cased_string(),
                          struct_name = 'struct PyGccTree',
                          tp_dealloc = 'NULL',
                          tp_repr = 'NULL',
                          tp_methods = 'NULL',
                          tp_init = 'NULL',
                          tp_new = 'PyType_GenericNew')
    cu.add_defn(pytype.c_defn())
    modinit_preinit += "\n    %s.tp_base = &gcc_TreeType;\n" % pytype.name
    modinit_preinit += pytype.c_invoke_type_ready()
    modinit_postinit += pytype.c_invoke_add_to_module()
    
cu.add_defn('\n/* Map from GCC tree codes to PyTypeObject* */\n')
cu.add_defn('PyTypeObject *pytype_for_tree_code[] = {\n')
for tree_type in tree_types:
    cu.add_defn('    &gcc_%sType, /* %s */\n' % (tree_type.camel_cased_string(), tree_type.SYM))
cu.add_defn('};\n\n')
cu.add_defn("""
PyTypeObject*
gcc_python_autogenerated_tree_type_for_tree(tree t)
{
    enum tree_code code = TREE_CODE(t);
    /* printf("code:%i\\n", code); */
    /* FIXME: range check */
    return pytype_for_tree_code[code];
}
""")


cu.add_defn("""
int gcc_python_autogenerated_tree_init_types(void)
{
""" + modinit_preinit + """
    return 1;

error:
    return 0;
}
""")

cu.add_defn("""
void gcc_python_autogenerated_tree_add_types(PyObject *m)
{
""" + modinit_postinit + """
}
""")

print(cu.as_str())
