from cpybuilder import *

cu = CompilationUnit()
cu.add_include('gcc-python.h')
cu.add_include('gcc-python-wrappers.h')
cu.add_include('gcc-plugin.h')

modinit_preinit = ''
modinit_postinit = ''

def generate_pretty_printer():
    global modinit_preinit
    global modinit_postinit
    
    pytype = PyTypeObject(identifier = 'gcc_PrettyPrinterType',
                          localname = 'PrettyPrinter',
                          tp_name = 'gcc.PrettyPrinter',
                          struct_name = 'struct PyGccPrettyPrinter',
                          tp_new = 'PyType_GenericNew',
                          tp_dealloc = 'gcc_PrettyPrinter_dealloc',
                          )
    cu.add_defn(pytype.c_defn())
    modinit_preinit += pytype.c_invoke_type_ready()
    modinit_postinit += pytype.c_invoke_add_to_module()
    
generate_pretty_printer()

cu.add_defn("""
int autogenerated_pretty_printer_init_types(void)
{
""" + modinit_preinit + """
    return 1;

error:
    return 0;
}
""")

cu.add_defn("""
void autogenerated_pretty_printer_add_types(PyObject *m)
{
""" + modinit_postinit + """
}
""")



print(cu.as_str())
