GCC=gcc

PLUGIN_SOURCE_FILES= \
  gcc-python.c \
  gcc-python-cfg.c \
  gcc-python-closure.c \
  gcc-python-function.c \
  gcc-python-gimple.c \
  gcc-python-location.c \
  gcc-python-pass.c \
  gcc-python-pretty-printer.c \
  gcc-python-tree.c \
  gcc-python-variable.c \
  autogenerated-cfg.c \
  autogenerated-function.c \
  autogenerated-gimple.c \
  autogenerated-location.c \
  autogenerated-pass.c \
  autogenerated-pretty-printer.c \
  autogenerated-tree.c \
  autogenerated-variable.c

PLUGIN_OBJECT_FILES= $(patsubst %.c,%.o,$(PLUGIN_SOURCE_FILES))
GCCPLUGINS_DIR:= $(shell $(GCC) --print-file-name=plugin)

PYTHON_CONFIG=python-debug-config
PYTHON_CFLAGS=$(shell $(PYTHON_CONFIG) --cflags)
PYTHON_LDFLAGS=$(shell $(PYTHON_CONFIG) --ldflags)

CFLAGS+= -I$(GCCPLUGINS_DIR)/include -fPIC -O2 -Wall -Werror -g $(PYTHON_CFLAGS) $(PYTHON_LDFLAGS)

all: testcpychecker testcpybuilder test-suite demo test

plugin: python.so

python.so: $(PLUGIN_OBJECT_FILES)
	$(GCC) $(CFLAGS) -shared $^ -o $@

clean:
	rm -f *.so *.o
	rm -f autogenerated*

autogenerated-gimple-types.txt: gimple-types.txt.in
	cpp $(CFLAGS) $^ -o $@

autogenerated-tree-types.txt: tree-types.txt.in
	cpp $(CFLAGS) $^ -o $@

autogenerated-cfg.c: cpybuilder.py generate-cfg-c.py
	python generate-cfg-c.py > $@

autogenerated-function.c: cpybuilder.py generate-function-c.py
	python generate-function-c.py > $@

autogenerated-gimple.c: cpybuilder.py generate-gimple-c.py autogenerated-gimple-types.txt maketreetypes.py
	python generate-gimple-c.py > $@

autogenerated-location.c: cpybuilder.py generate-location-c.py
	python generate-location-c.py > $@

autogenerated-pass.c: cpybuilder.py generate-pass-c.py
	python generate-pass-c.py > $@

autogenerated-pretty-printer.c: cpybuilder.py generate-pretty-printer-c.py
	python generate-pretty-printer-c.py > $@

autogenerated-tree.c: cpybuilder.py generate-tree-c.py autogenerated-tree-types.txt maketreetypes.py
	python generate-tree-c.py > $@

autogenerated-variable.c: cpybuilder.py generate-variable-c.py autogenerated-gimple-types.txt maketreetypes.py
	python generate-variable-c.py > $@

# Hint for debugging: add -v to the gcc options 
# to get a command line for invoking individual subprocesses
# Doing so seems to require that paths be absolute, rather than relative
# to this directory
TEST_CFLAGS= \
  -fplugin=$(shell pwd)/python.so \
  -fplugin-arg-python-script=test.py

# Catch-all test for experimentation with the API:
test: plugin
	PYTHONPATH=$(shell pwd) gcc -v $(TEST_CFLAGS) $(shell pwd)/test.c

# Selftest for the cpychecker.py code:
testcpychecker: plugin
	PYTHONPATH=$(shell pwd) python testcpychecker.py -v

# Selftest for the cpybuilder code:
testcpybuilder:
	python testcpybuilder.py -v

dump_gimple:
	gcc -fdump-tree-gimple $(shell pwd)/test.c

debug: plugin
	PYTHONPATH=$(shell pwd) gcc -v $(TEST_CFLAGS) $(shell pwd)/test.c

# A simple demo, to make it easy to demonstrate the cpychecker:
demo: plugin
	PYTHONPATH=$(shell pwd) gcc -fplugin=$(shell pwd)/python.so -fplugin-arg-python-script=cpychecker.py $(shell python-config --cflags) $(shell pwd)/demo.c

test-suite: plugin
	python run-test-suite.py

show-ssa: plugin
	./gcc-with-python show-ssa.py test.c
